// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package er

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sbercloud-terraform/pulumi-cloudru/sdk/go/sbercloud/internal"
)

// Manages an association resource under the route table for ER service within SberCloud.
//
// Before using enterprise router, define custom endpoint as shown below:
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			return nil
//		})
//	}
//
// ```
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//	"github.com/sbercloud-terraform/pulumi-cloudru/sdk/go/sbercloud/er"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			instanceId := cfg.RequireObject("instanceId")
//			routeTableId := cfg.RequireObject("routeTableId")
//			attachmentId := cfg.RequireObject("attachmentId")
//			_, err := er.NewAssociation(ctx, "test", &er.AssociationArgs{
//				InstanceId:   pulumi.Any(instanceId),
//				RouteTableId: pulumi.Any(routeTableId),
//				AttachmentId: pulumi.Any(attachmentId),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Associations can be imported using their `id` and the related `instance_id` and `route_table_id`, separated by
//
// slashes (/), e.g.
//
// bash
//
// ```sh
// $ pulumi import sbercloud:Er/association:Association test <instance_id>/<route_table_id>/<id>
// ```
type Association struct {
	pulumi.CustomResourceState

	// Specifies the ID of the attachment corresponding to the association.\
	// Changing this parameter will create a new resource.
	AttachmentId pulumi.StringOutput `pulumi:"attachmentId"`
	// The type of the attachment corresponding to the association.
	AttachmentType pulumi.StringOutput `pulumi:"attachmentType"`
	// The creation time.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Specifies the ID of the ER instance to which the route table and the
	// attachment belongs.
	// Changing this parameter will create a new resource.
	InstanceId pulumi.StringOutput `pulumi:"instanceId"`
	// Specifies the region where the ER instance and route table are located.\
	// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
	Region pulumi.StringOutput `pulumi:"region"`
	// Specifies the ID of the route table to which the association
	// belongs.
	// Changing this parameter will create a new resource.
	RouteTableId pulumi.StringOutput `pulumi:"routeTableId"`
	// The current status of the association.
	Status pulumi.StringOutput `pulumi:"status"`
	// The latest update time.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewAssociation registers a new resource with the given unique name, arguments, and options.
func NewAssociation(ctx *pulumi.Context,
	name string, args *AssociationArgs, opts ...pulumi.ResourceOption) (*Association, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AttachmentId == nil {
		return nil, errors.New("invalid value for required argument 'AttachmentId'")
	}
	if args.InstanceId == nil {
		return nil, errors.New("invalid value for required argument 'InstanceId'")
	}
	if args.RouteTableId == nil {
		return nil, errors.New("invalid value for required argument 'RouteTableId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Association
	err := ctx.RegisterResource("sbercloud:Er/association:Association", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAssociation gets an existing Association resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAssociation(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AssociationState, opts ...pulumi.ResourceOption) (*Association, error) {
	var resource Association
	err := ctx.ReadResource("sbercloud:Er/association:Association", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Association resources.
type associationState struct {
	// Specifies the ID of the attachment corresponding to the association.\
	// Changing this parameter will create a new resource.
	AttachmentId *string `pulumi:"attachmentId"`
	// The type of the attachment corresponding to the association.
	AttachmentType *string `pulumi:"attachmentType"`
	// The creation time.
	CreatedAt *string `pulumi:"createdAt"`
	// Specifies the ID of the ER instance to which the route table and the
	// attachment belongs.
	// Changing this parameter will create a new resource.
	InstanceId *string `pulumi:"instanceId"`
	// Specifies the region where the ER instance and route table are located.\
	// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
	Region *string `pulumi:"region"`
	// Specifies the ID of the route table to which the association
	// belongs.
	// Changing this parameter will create a new resource.
	RouteTableId *string `pulumi:"routeTableId"`
	// The current status of the association.
	Status *string `pulumi:"status"`
	// The latest update time.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type AssociationState struct {
	// Specifies the ID of the attachment corresponding to the association.\
	// Changing this parameter will create a new resource.
	AttachmentId pulumi.StringPtrInput
	// The type of the attachment corresponding to the association.
	AttachmentType pulumi.StringPtrInput
	// The creation time.
	CreatedAt pulumi.StringPtrInput
	// Specifies the ID of the ER instance to which the route table and the
	// attachment belongs.
	// Changing this parameter will create a new resource.
	InstanceId pulumi.StringPtrInput
	// Specifies the region where the ER instance and route table are located.\
	// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
	Region pulumi.StringPtrInput
	// Specifies the ID of the route table to which the association
	// belongs.
	// Changing this parameter will create a new resource.
	RouteTableId pulumi.StringPtrInput
	// The current status of the association.
	Status pulumi.StringPtrInput
	// The latest update time.
	UpdatedAt pulumi.StringPtrInput
}

func (AssociationState) ElementType() reflect.Type {
	return reflect.TypeOf((*associationState)(nil)).Elem()
}

type associationArgs struct {
	// Specifies the ID of the attachment corresponding to the association.\
	// Changing this parameter will create a new resource.
	AttachmentId string `pulumi:"attachmentId"`
	// Specifies the ID of the ER instance to which the route table and the
	// attachment belongs.
	// Changing this parameter will create a new resource.
	InstanceId string `pulumi:"instanceId"`
	// Specifies the region where the ER instance and route table are located.\
	// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
	Region *string `pulumi:"region"`
	// Specifies the ID of the route table to which the association
	// belongs.
	// Changing this parameter will create a new resource.
	RouteTableId string `pulumi:"routeTableId"`
}

// The set of arguments for constructing a Association resource.
type AssociationArgs struct {
	// Specifies the ID of the attachment corresponding to the association.\
	// Changing this parameter will create a new resource.
	AttachmentId pulumi.StringInput
	// Specifies the ID of the ER instance to which the route table and the
	// attachment belongs.
	// Changing this parameter will create a new resource.
	InstanceId pulumi.StringInput
	// Specifies the region where the ER instance and route table are located.\
	// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
	Region pulumi.StringPtrInput
	// Specifies the ID of the route table to which the association
	// belongs.
	// Changing this parameter will create a new resource.
	RouteTableId pulumi.StringInput
}

func (AssociationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*associationArgs)(nil)).Elem()
}

type AssociationInput interface {
	pulumi.Input

	ToAssociationOutput() AssociationOutput
	ToAssociationOutputWithContext(ctx context.Context) AssociationOutput
}

func (*Association) ElementType() reflect.Type {
	return reflect.TypeOf((**Association)(nil)).Elem()
}

func (i *Association) ToAssociationOutput() AssociationOutput {
	return i.ToAssociationOutputWithContext(context.Background())
}

func (i *Association) ToAssociationOutputWithContext(ctx context.Context) AssociationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssociationOutput)
}

// AssociationArrayInput is an input type that accepts AssociationArray and AssociationArrayOutput values.
// You can construct a concrete instance of `AssociationArrayInput` via:
//
//	AssociationArray{ AssociationArgs{...} }
type AssociationArrayInput interface {
	pulumi.Input

	ToAssociationArrayOutput() AssociationArrayOutput
	ToAssociationArrayOutputWithContext(context.Context) AssociationArrayOutput
}

type AssociationArray []AssociationInput

func (AssociationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Association)(nil)).Elem()
}

func (i AssociationArray) ToAssociationArrayOutput() AssociationArrayOutput {
	return i.ToAssociationArrayOutputWithContext(context.Background())
}

func (i AssociationArray) ToAssociationArrayOutputWithContext(ctx context.Context) AssociationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssociationArrayOutput)
}

// AssociationMapInput is an input type that accepts AssociationMap and AssociationMapOutput values.
// You can construct a concrete instance of `AssociationMapInput` via:
//
//	AssociationMap{ "key": AssociationArgs{...} }
type AssociationMapInput interface {
	pulumi.Input

	ToAssociationMapOutput() AssociationMapOutput
	ToAssociationMapOutputWithContext(context.Context) AssociationMapOutput
}

type AssociationMap map[string]AssociationInput

func (AssociationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Association)(nil)).Elem()
}

func (i AssociationMap) ToAssociationMapOutput() AssociationMapOutput {
	return i.ToAssociationMapOutputWithContext(context.Background())
}

func (i AssociationMap) ToAssociationMapOutputWithContext(ctx context.Context) AssociationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssociationMapOutput)
}

type AssociationOutput struct{ *pulumi.OutputState }

func (AssociationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Association)(nil)).Elem()
}

func (o AssociationOutput) ToAssociationOutput() AssociationOutput {
	return o
}

func (o AssociationOutput) ToAssociationOutputWithContext(ctx context.Context) AssociationOutput {
	return o
}

// Specifies the ID of the attachment corresponding to the association.\
// Changing this parameter will create a new resource.
func (o AssociationOutput) AttachmentId() pulumi.StringOutput {
	return o.ApplyT(func(v *Association) pulumi.StringOutput { return v.AttachmentId }).(pulumi.StringOutput)
}

// The type of the attachment corresponding to the association.
func (o AssociationOutput) AttachmentType() pulumi.StringOutput {
	return o.ApplyT(func(v *Association) pulumi.StringOutput { return v.AttachmentType }).(pulumi.StringOutput)
}

// The creation time.
func (o AssociationOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Association) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Specifies the ID of the ER instance to which the route table and the
// attachment belongs.
// Changing this parameter will create a new resource.
func (o AssociationOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *Association) pulumi.StringOutput { return v.InstanceId }).(pulumi.StringOutput)
}

// Specifies the region where the ER instance and route table are located.\
// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
func (o AssociationOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Association) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// Specifies the ID of the route table to which the association
// belongs.
// Changing this parameter will create a new resource.
func (o AssociationOutput) RouteTableId() pulumi.StringOutput {
	return o.ApplyT(func(v *Association) pulumi.StringOutput { return v.RouteTableId }).(pulumi.StringOutput)
}

// The current status of the association.
func (o AssociationOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Association) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// The latest update time.
func (o AssociationOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Association) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type AssociationArrayOutput struct{ *pulumi.OutputState }

func (AssociationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Association)(nil)).Elem()
}

func (o AssociationArrayOutput) ToAssociationArrayOutput() AssociationArrayOutput {
	return o
}

func (o AssociationArrayOutput) ToAssociationArrayOutputWithContext(ctx context.Context) AssociationArrayOutput {
	return o
}

func (o AssociationArrayOutput) Index(i pulumi.IntInput) AssociationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Association {
		return vs[0].([]*Association)[vs[1].(int)]
	}).(AssociationOutput)
}

type AssociationMapOutput struct{ *pulumi.OutputState }

func (AssociationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Association)(nil)).Elem()
}

func (o AssociationMapOutput) ToAssociationMapOutput() AssociationMapOutput {
	return o
}

func (o AssociationMapOutput) ToAssociationMapOutputWithContext(ctx context.Context) AssociationMapOutput {
	return o
}

func (o AssociationMapOutput) MapIndex(k pulumi.StringInput) AssociationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Association {
		return vs[0].(map[string]*Association)[vs[1].(string)]
	}).(AssociationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AssociationInput)(nil)).Elem(), &Association{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssociationArrayInput)(nil)).Elem(), AssociationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssociationMapInput)(nil)).Elem(), AssociationMap{})
	pulumi.RegisterOutputType(AssociationOutput{})
	pulumi.RegisterOutputType(AssociationArrayOutput{})
	pulumi.RegisterOutputType(AssociationMapOutput{})
}
