// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vpc

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sbercloud-terraform/pulumi-cloudru/sdk/go/cloudru/internal"
)

func LookupSecgroup(ctx *pulumi.Context, args *LookupSecgroupArgs, opts ...pulumi.InvokeOption) (*LookupSecgroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSecgroupResult
	err := ctx.Invoke("cloudru:Vpc/getSecgroup:getSecgroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSecgroup.
type LookupSecgroupArgs struct {
	EnterpriseProjectId *string `pulumi:"enterpriseProjectId"`
	Name                *string `pulumi:"name"`
	Region              *string `pulumi:"region"`
	SecgroupId          *string `pulumi:"secgroupId"`
}

// A collection of values returned by getSecgroup.
type LookupSecgroupResult struct {
	CreatedAt           string  `pulumi:"createdAt"`
	Description         string  `pulumi:"description"`
	EnterpriseProjectId *string `pulumi:"enterpriseProjectId"`
	// The provider-assigned unique ID for this managed resource.
	Id         string                `pulumi:"id"`
	Name       string                `pulumi:"name"`
	Region     string                `pulumi:"region"`
	Rules      []GetSecgroupRuleType `pulumi:"rules"`
	SecgroupId *string               `pulumi:"secgroupId"`
	UpdatedAt  string                `pulumi:"updatedAt"`
}

func LookupSecgroupOutput(ctx *pulumi.Context, args LookupSecgroupOutputArgs, opts ...pulumi.InvokeOption) LookupSecgroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSecgroupResultOutput, error) {
			args := v.(LookupSecgroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cloudru:Vpc/getSecgroup:getSecgroup", args, LookupSecgroupResultOutput{}, options).(LookupSecgroupResultOutput), nil
		}).(LookupSecgroupResultOutput)
}

// A collection of arguments for invoking getSecgroup.
type LookupSecgroupOutputArgs struct {
	EnterpriseProjectId pulumi.StringPtrInput `pulumi:"enterpriseProjectId"`
	Name                pulumi.StringPtrInput `pulumi:"name"`
	Region              pulumi.StringPtrInput `pulumi:"region"`
	SecgroupId          pulumi.StringPtrInput `pulumi:"secgroupId"`
}

func (LookupSecgroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecgroupArgs)(nil)).Elem()
}

// A collection of values returned by getSecgroup.
type LookupSecgroupResultOutput struct{ *pulumi.OutputState }

func (LookupSecgroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecgroupResult)(nil)).Elem()
}

func (o LookupSecgroupResultOutput) ToLookupSecgroupResultOutput() LookupSecgroupResultOutput {
	return o
}

func (o LookupSecgroupResultOutput) ToLookupSecgroupResultOutputWithContext(ctx context.Context) LookupSecgroupResultOutput {
	return o
}

func (o LookupSecgroupResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecgroupResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupSecgroupResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecgroupResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupSecgroupResultOutput) EnterpriseProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecgroupResult) *string { return v.EnterpriseProjectId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSecgroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecgroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSecgroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecgroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSecgroupResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecgroupResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupSecgroupResultOutput) Rules() GetSecgroupRuleTypeArrayOutput {
	return o.ApplyT(func(v LookupSecgroupResult) []GetSecgroupRuleType { return v.Rules }).(GetSecgroupRuleTypeArrayOutput)
}

func (o LookupSecgroupResultOutput) SecgroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecgroupResult) *string { return v.SecgroupId }).(pulumi.StringPtrOutput)
}

func (o LookupSecgroupResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecgroupResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSecgroupResultOutput{})
}
