// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloudru

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sbercloud-terraform/pulumi-cloudru/sdk/go/cloudru/internal"
)

// Manages the function trigger resource within SberCloud.
//
// ## Example Usage
//
// ## Import
//
// Function trigger can be imported using the `function_urn`, `type` and `id`, separated by the slashes (/), e.g.
//
// bash
//
// ```sh
// $ pulumi import sbercloud:index/fgsFunctionTrigger:FgsFunctionTrigger test <function_urn>/<type>/<id>
// ```
type FgsFunctionTrigger struct {
	pulumi.CustomResourceState

	// The creation time of the function trigger.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Specifies the detailed configuration of the function trigger event, in JSON
	// format.
	// For various types of trigger parameter configurations, please refer to the
	// [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#functiongraph_06_0122__request_TriggerEventDataRequestBody).
	//
	// > Please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0124.html#functiongraph_06_0124__request_UpdateriggerEventData)
	// for updateable fields.
	EventData pulumi.StringOutput `pulumi:"eventData"`
	// Specifies the function URN to which the function trigger belongs.\
	// Changing this will create a new resource.
	FunctionUrn pulumi.StringOutput `pulumi:"functionUrn"`
	// Specifies the region where the function trigger is located.\
	// If omitted, the provider-level region will be used. Changing this will create a new resource.
	Region pulumi.StringOutput `pulumi:"region"`
	// Specifies the status of the function trigger.\
	// The valid values are **ACTIVE** and **DISABLED**.
	// About `DDS` and `Kafka` triggers, the default value is **DISABLED**, for the other triggers, the default value is
	// **ACTIVE**.
	//
	// > Currently, only some triggers support setting the **DISABLED** value, such as `TIMER`, `DDS`, `DMS`, `KAFKA` and
	// `LTS`. For more details, please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html).
	Status pulumi.StringOutput `pulumi:"status"`
	// Specifies the type of the function trigger.\
	// The valid values are **TIMER**, **APIG**, **CTS**, **DDS**, **DEDICATEDGATEWAY**, etc.
	// Changing this will create a new resource.
	//
	// > For more available values, please refer to the [documentation table 3](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#section2).
	Type pulumi.StringOutput `pulumi:"type"`
	// The latest update time of the function trigger.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewFgsFunctionTrigger registers a new resource with the given unique name, arguments, and options.
func NewFgsFunctionTrigger(ctx *pulumi.Context,
	name string, args *FgsFunctionTriggerArgs, opts ...pulumi.ResourceOption) (*FgsFunctionTrigger, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EventData == nil {
		return nil, errors.New("invalid value for required argument 'EventData'")
	}
	if args.FunctionUrn == nil {
		return nil, errors.New("invalid value for required argument 'FunctionUrn'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FgsFunctionTrigger
	err := ctx.RegisterResource("sbercloud:index/fgsFunctionTrigger:FgsFunctionTrigger", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFgsFunctionTrigger gets an existing FgsFunctionTrigger resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFgsFunctionTrigger(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FgsFunctionTriggerState, opts ...pulumi.ResourceOption) (*FgsFunctionTrigger, error) {
	var resource FgsFunctionTrigger
	err := ctx.ReadResource("sbercloud:index/fgsFunctionTrigger:FgsFunctionTrigger", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FgsFunctionTrigger resources.
type fgsFunctionTriggerState struct {
	// The creation time of the function trigger.
	CreatedAt *string `pulumi:"createdAt"`
	// Specifies the detailed configuration of the function trigger event, in JSON
	// format.
	// For various types of trigger parameter configurations, please refer to the
	// [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#functiongraph_06_0122__request_TriggerEventDataRequestBody).
	//
	// > Please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0124.html#functiongraph_06_0124__request_UpdateriggerEventData)
	// for updateable fields.
	EventData *string `pulumi:"eventData"`
	// Specifies the function URN to which the function trigger belongs.\
	// Changing this will create a new resource.
	FunctionUrn *string `pulumi:"functionUrn"`
	// Specifies the region where the function trigger is located.\
	// If omitted, the provider-level region will be used. Changing this will create a new resource.
	Region *string `pulumi:"region"`
	// Specifies the status of the function trigger.\
	// The valid values are **ACTIVE** and **DISABLED**.
	// About `DDS` and `Kafka` triggers, the default value is **DISABLED**, for the other triggers, the default value is
	// **ACTIVE**.
	//
	// > Currently, only some triggers support setting the **DISABLED** value, such as `TIMER`, `DDS`, `DMS`, `KAFKA` and
	// `LTS`. For more details, please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html).
	Status *string `pulumi:"status"`
	// Specifies the type of the function trigger.\
	// The valid values are **TIMER**, **APIG**, **CTS**, **DDS**, **DEDICATEDGATEWAY**, etc.
	// Changing this will create a new resource.
	//
	// > For more available values, please refer to the [documentation table 3](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#section2).
	Type *string `pulumi:"type"`
	// The latest update time of the function trigger.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type FgsFunctionTriggerState struct {
	// The creation time of the function trigger.
	CreatedAt pulumi.StringPtrInput
	// Specifies the detailed configuration of the function trigger event, in JSON
	// format.
	// For various types of trigger parameter configurations, please refer to the
	// [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#functiongraph_06_0122__request_TriggerEventDataRequestBody).
	//
	// > Please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0124.html#functiongraph_06_0124__request_UpdateriggerEventData)
	// for updateable fields.
	EventData pulumi.StringPtrInput
	// Specifies the function URN to which the function trigger belongs.\
	// Changing this will create a new resource.
	FunctionUrn pulumi.StringPtrInput
	// Specifies the region where the function trigger is located.\
	// If omitted, the provider-level region will be used. Changing this will create a new resource.
	Region pulumi.StringPtrInput
	// Specifies the status of the function trigger.\
	// The valid values are **ACTIVE** and **DISABLED**.
	// About `DDS` and `Kafka` triggers, the default value is **DISABLED**, for the other triggers, the default value is
	// **ACTIVE**.
	//
	// > Currently, only some triggers support setting the **DISABLED** value, such as `TIMER`, `DDS`, `DMS`, `KAFKA` and
	// `LTS`. For more details, please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html).
	Status pulumi.StringPtrInput
	// Specifies the type of the function trigger.\
	// The valid values are **TIMER**, **APIG**, **CTS**, **DDS**, **DEDICATEDGATEWAY**, etc.
	// Changing this will create a new resource.
	//
	// > For more available values, please refer to the [documentation table 3](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#section2).
	Type pulumi.StringPtrInput
	// The latest update time of the function trigger.
	UpdatedAt pulumi.StringPtrInput
}

func (FgsFunctionTriggerState) ElementType() reflect.Type {
	return reflect.TypeOf((*fgsFunctionTriggerState)(nil)).Elem()
}

type fgsFunctionTriggerArgs struct {
	// Specifies the detailed configuration of the function trigger event, in JSON
	// format.
	// For various types of trigger parameter configurations, please refer to the
	// [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#functiongraph_06_0122__request_TriggerEventDataRequestBody).
	//
	// > Please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0124.html#functiongraph_06_0124__request_UpdateriggerEventData)
	// for updateable fields.
	EventData string `pulumi:"eventData"`
	// Specifies the function URN to which the function trigger belongs.\
	// Changing this will create a new resource.
	FunctionUrn string `pulumi:"functionUrn"`
	// Specifies the region where the function trigger is located.\
	// If omitted, the provider-level region will be used. Changing this will create a new resource.
	Region *string `pulumi:"region"`
	// Specifies the status of the function trigger.\
	// The valid values are **ACTIVE** and **DISABLED**.
	// About `DDS` and `Kafka` triggers, the default value is **DISABLED**, for the other triggers, the default value is
	// **ACTIVE**.
	//
	// > Currently, only some triggers support setting the **DISABLED** value, such as `TIMER`, `DDS`, `DMS`, `KAFKA` and
	// `LTS`. For more details, please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html).
	Status *string `pulumi:"status"`
	// Specifies the type of the function trigger.\
	// The valid values are **TIMER**, **APIG**, **CTS**, **DDS**, **DEDICATEDGATEWAY**, etc.
	// Changing this will create a new resource.
	//
	// > For more available values, please refer to the [documentation table 3](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#section2).
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a FgsFunctionTrigger resource.
type FgsFunctionTriggerArgs struct {
	// Specifies the detailed configuration of the function trigger event, in JSON
	// format.
	// For various types of trigger parameter configurations, please refer to the
	// [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#functiongraph_06_0122__request_TriggerEventDataRequestBody).
	//
	// > Please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0124.html#functiongraph_06_0124__request_UpdateriggerEventData)
	// for updateable fields.
	EventData pulumi.StringInput
	// Specifies the function URN to which the function trigger belongs.\
	// Changing this will create a new resource.
	FunctionUrn pulumi.StringInput
	// Specifies the region where the function trigger is located.\
	// If omitted, the provider-level region will be used. Changing this will create a new resource.
	Region pulumi.StringPtrInput
	// Specifies the status of the function trigger.\
	// The valid values are **ACTIVE** and **DISABLED**.
	// About `DDS` and `Kafka` triggers, the default value is **DISABLED**, for the other triggers, the default value is
	// **ACTIVE**.
	//
	// > Currently, only some triggers support setting the **DISABLED** value, such as `TIMER`, `DDS`, `DMS`, `KAFKA` and
	// `LTS`. For more details, please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html).
	Status pulumi.StringPtrInput
	// Specifies the type of the function trigger.\
	// The valid values are **TIMER**, **APIG**, **CTS**, **DDS**, **DEDICATEDGATEWAY**, etc.
	// Changing this will create a new resource.
	//
	// > For more available values, please refer to the [documentation table 3](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#section2).
	Type pulumi.StringInput
}

func (FgsFunctionTriggerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*fgsFunctionTriggerArgs)(nil)).Elem()
}

type FgsFunctionTriggerInput interface {
	pulumi.Input

	ToFgsFunctionTriggerOutput() FgsFunctionTriggerOutput
	ToFgsFunctionTriggerOutputWithContext(ctx context.Context) FgsFunctionTriggerOutput
}

func (*FgsFunctionTrigger) ElementType() reflect.Type {
	return reflect.TypeOf((**FgsFunctionTrigger)(nil)).Elem()
}

func (i *FgsFunctionTrigger) ToFgsFunctionTriggerOutput() FgsFunctionTriggerOutput {
	return i.ToFgsFunctionTriggerOutputWithContext(context.Background())
}

func (i *FgsFunctionTrigger) ToFgsFunctionTriggerOutputWithContext(ctx context.Context) FgsFunctionTriggerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FgsFunctionTriggerOutput)
}

// FgsFunctionTriggerArrayInput is an input type that accepts FgsFunctionTriggerArray and FgsFunctionTriggerArrayOutput values.
// You can construct a concrete instance of `FgsFunctionTriggerArrayInput` via:
//
//	FgsFunctionTriggerArray{ FgsFunctionTriggerArgs{...} }
type FgsFunctionTriggerArrayInput interface {
	pulumi.Input

	ToFgsFunctionTriggerArrayOutput() FgsFunctionTriggerArrayOutput
	ToFgsFunctionTriggerArrayOutputWithContext(context.Context) FgsFunctionTriggerArrayOutput
}

type FgsFunctionTriggerArray []FgsFunctionTriggerInput

func (FgsFunctionTriggerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FgsFunctionTrigger)(nil)).Elem()
}

func (i FgsFunctionTriggerArray) ToFgsFunctionTriggerArrayOutput() FgsFunctionTriggerArrayOutput {
	return i.ToFgsFunctionTriggerArrayOutputWithContext(context.Background())
}

func (i FgsFunctionTriggerArray) ToFgsFunctionTriggerArrayOutputWithContext(ctx context.Context) FgsFunctionTriggerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FgsFunctionTriggerArrayOutput)
}

// FgsFunctionTriggerMapInput is an input type that accepts FgsFunctionTriggerMap and FgsFunctionTriggerMapOutput values.
// You can construct a concrete instance of `FgsFunctionTriggerMapInput` via:
//
//	FgsFunctionTriggerMap{ "key": FgsFunctionTriggerArgs{...} }
type FgsFunctionTriggerMapInput interface {
	pulumi.Input

	ToFgsFunctionTriggerMapOutput() FgsFunctionTriggerMapOutput
	ToFgsFunctionTriggerMapOutputWithContext(context.Context) FgsFunctionTriggerMapOutput
}

type FgsFunctionTriggerMap map[string]FgsFunctionTriggerInput

func (FgsFunctionTriggerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FgsFunctionTrigger)(nil)).Elem()
}

func (i FgsFunctionTriggerMap) ToFgsFunctionTriggerMapOutput() FgsFunctionTriggerMapOutput {
	return i.ToFgsFunctionTriggerMapOutputWithContext(context.Background())
}

func (i FgsFunctionTriggerMap) ToFgsFunctionTriggerMapOutputWithContext(ctx context.Context) FgsFunctionTriggerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FgsFunctionTriggerMapOutput)
}

type FgsFunctionTriggerOutput struct{ *pulumi.OutputState }

func (FgsFunctionTriggerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FgsFunctionTrigger)(nil)).Elem()
}

func (o FgsFunctionTriggerOutput) ToFgsFunctionTriggerOutput() FgsFunctionTriggerOutput {
	return o
}

func (o FgsFunctionTriggerOutput) ToFgsFunctionTriggerOutputWithContext(ctx context.Context) FgsFunctionTriggerOutput {
	return o
}

// The creation time of the function trigger.
func (o FgsFunctionTriggerOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *FgsFunctionTrigger) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Specifies the detailed configuration of the function trigger event, in JSON
// format.
// For various types of trigger parameter configurations, please refer to the
// [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#functiongraph_06_0122__request_TriggerEventDataRequestBody).
//
// > Please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0124.html#functiongraph_06_0124__request_UpdateriggerEventData)
// for updateable fields.
func (o FgsFunctionTriggerOutput) EventData() pulumi.StringOutput {
	return o.ApplyT(func(v *FgsFunctionTrigger) pulumi.StringOutput { return v.EventData }).(pulumi.StringOutput)
}

// Specifies the function URN to which the function trigger belongs.\
// Changing this will create a new resource.
func (o FgsFunctionTriggerOutput) FunctionUrn() pulumi.StringOutput {
	return o.ApplyT(func(v *FgsFunctionTrigger) pulumi.StringOutput { return v.FunctionUrn }).(pulumi.StringOutput)
}

// Specifies the region where the function trigger is located.\
// If omitted, the provider-level region will be used. Changing this will create a new resource.
func (o FgsFunctionTriggerOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *FgsFunctionTrigger) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// Specifies the status of the function trigger.\
// The valid values are **ACTIVE** and **DISABLED**.
// About `DDS` and `Kafka` triggers, the default value is **DISABLED**, for the other triggers, the default value is
// **ACTIVE**.
//
// > Currently, only some triggers support setting the **DISABLED** value, such as `TIMER`, `DDS`, `DMS`, `KAFKA` and
// `LTS`. For more details, please refer to the [documentation](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html).
func (o FgsFunctionTriggerOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *FgsFunctionTrigger) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Specifies the type of the function trigger.\
// The valid values are **TIMER**, **APIG**, **CTS**, **DDS**, **DEDICATEDGATEWAY**, etc.
// Changing this will create a new resource.
//
// > For more available values, please refer to the [documentation table 3](https://support.sbercloud.com/intl/en-us/api-functiongraph/functiongraph_06_0122.html#section2).
func (o FgsFunctionTriggerOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *FgsFunctionTrigger) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// The latest update time of the function trigger.
func (o FgsFunctionTriggerOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *FgsFunctionTrigger) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type FgsFunctionTriggerArrayOutput struct{ *pulumi.OutputState }

func (FgsFunctionTriggerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FgsFunctionTrigger)(nil)).Elem()
}

func (o FgsFunctionTriggerArrayOutput) ToFgsFunctionTriggerArrayOutput() FgsFunctionTriggerArrayOutput {
	return o
}

func (o FgsFunctionTriggerArrayOutput) ToFgsFunctionTriggerArrayOutputWithContext(ctx context.Context) FgsFunctionTriggerArrayOutput {
	return o
}

func (o FgsFunctionTriggerArrayOutput) Index(i pulumi.IntInput) FgsFunctionTriggerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FgsFunctionTrigger {
		return vs[0].([]*FgsFunctionTrigger)[vs[1].(int)]
	}).(FgsFunctionTriggerOutput)
}

type FgsFunctionTriggerMapOutput struct{ *pulumi.OutputState }

func (FgsFunctionTriggerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FgsFunctionTrigger)(nil)).Elem()
}

func (o FgsFunctionTriggerMapOutput) ToFgsFunctionTriggerMapOutput() FgsFunctionTriggerMapOutput {
	return o
}

func (o FgsFunctionTriggerMapOutput) ToFgsFunctionTriggerMapOutputWithContext(ctx context.Context) FgsFunctionTriggerMapOutput {
	return o
}

func (o FgsFunctionTriggerMapOutput) MapIndex(k pulumi.StringInput) FgsFunctionTriggerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FgsFunctionTrigger {
		return vs[0].(map[string]*FgsFunctionTrigger)[vs[1].(string)]
	}).(FgsFunctionTriggerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FgsFunctionTriggerInput)(nil)).Elem(), &FgsFunctionTrigger{})
	pulumi.RegisterInputType(reflect.TypeOf((*FgsFunctionTriggerArrayInput)(nil)).Elem(), FgsFunctionTriggerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FgsFunctionTriggerMapInput)(nil)).Elem(), FgsFunctionTriggerMap{})
	pulumi.RegisterOutputType(FgsFunctionTriggerOutput{})
	pulumi.RegisterOutputType(FgsFunctionTriggerArrayOutput{})
	pulumi.RegisterOutputType(FgsFunctionTriggerMapOutput{})
}
