// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloudru

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sbercloud-terraform/pulumi-cloudru/sdk/go/cloudru/internal"
)

func LookupApigApplicationAcl(ctx *pulumi.Context, args *LookupApigApplicationAclArgs, opts ...pulumi.InvokeOption) (*LookupApigApplicationAclResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupApigApplicationAclResult
	err := ctx.Invoke("cloudru:index/getApigApplicationAcl:getApigApplicationAcl", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApigApplicationAcl.
type LookupApigApplicationAclArgs struct {
	ApplicationId string  `pulumi:"applicationId"`
	InstanceId    string  `pulumi:"instanceId"`
	Region        *string `pulumi:"region"`
}

// A collection of values returned by getApigApplicationAcl.
type LookupApigApplicationAclResult struct {
	ApplicationId string `pulumi:"applicationId"`
	// The provider-assigned unique ID for this managed resource.
	Id         string   `pulumi:"id"`
	InstanceId string   `pulumi:"instanceId"`
	Region     string   `pulumi:"region"`
	Type       string   `pulumi:"type"`
	Values     []string `pulumi:"values"`
}

func LookupApigApplicationAclOutput(ctx *pulumi.Context, args LookupApigApplicationAclOutputArgs, opts ...pulumi.InvokeOption) LookupApigApplicationAclResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupApigApplicationAclResultOutput, error) {
			args := v.(LookupApigApplicationAclArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cloudru:index/getApigApplicationAcl:getApigApplicationAcl", args, LookupApigApplicationAclResultOutput{}, options).(LookupApigApplicationAclResultOutput), nil
		}).(LookupApigApplicationAclResultOutput)
}

// A collection of arguments for invoking getApigApplicationAcl.
type LookupApigApplicationAclOutputArgs struct {
	ApplicationId pulumi.StringInput    `pulumi:"applicationId"`
	InstanceId    pulumi.StringInput    `pulumi:"instanceId"`
	Region        pulumi.StringPtrInput `pulumi:"region"`
}

func (LookupApigApplicationAclOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApigApplicationAclArgs)(nil)).Elem()
}

// A collection of values returned by getApigApplicationAcl.
type LookupApigApplicationAclResultOutput struct{ *pulumi.OutputState }

func (LookupApigApplicationAclResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApigApplicationAclResult)(nil)).Elem()
}

func (o LookupApigApplicationAclResultOutput) ToLookupApigApplicationAclResultOutput() LookupApigApplicationAclResultOutput {
	return o
}

func (o LookupApigApplicationAclResultOutput) ToLookupApigApplicationAclResultOutputWithContext(ctx context.Context) LookupApigApplicationAclResultOutput {
	return o
}

func (o LookupApigApplicationAclResultOutput) ApplicationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApigApplicationAclResult) string { return v.ApplicationId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupApigApplicationAclResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApigApplicationAclResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupApigApplicationAclResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApigApplicationAclResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o LookupApigApplicationAclResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApigApplicationAclResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupApigApplicationAclResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApigApplicationAclResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o LookupApigApplicationAclResultOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApigApplicationAclResult) []string { return v.Values }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApigApplicationAclResultOutput{})
}
