// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cfw

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sbercloud-terraform/pulumi-cloudru/sdk/go/cloudru/internal"
)

func GetServiceGroupMembers(ctx *pulumi.Context, args *GetServiceGroupMembersArgs, opts ...pulumi.InvokeOption) (*GetServiceGroupMembersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetServiceGroupMembersResult
	err := ctx.Invoke("cloudru:Cfw/getServiceGroupMembers:getServiceGroupMembers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServiceGroupMembers.
type GetServiceGroupMembersArgs struct {
	DestPort     *string `pulumi:"destPort"`
	FwInstanceId *string `pulumi:"fwInstanceId"`
	GroupId      string  `pulumi:"groupId"`
	GroupType    *string `pulumi:"groupType"`
	ItemId       *string `pulumi:"itemId"`
	KeyWord      *string `pulumi:"keyWord"`
	Protocol     *int    `pulumi:"protocol"`
	Region       *string `pulumi:"region"`
	SourcePort   *string `pulumi:"sourcePort"`
}

// A collection of values returned by getServiceGroupMembers.
type GetServiceGroupMembersResult struct {
	DestPort     *string `pulumi:"destPort"`
	FwInstanceId *string `pulumi:"fwInstanceId"`
	GroupId      string  `pulumi:"groupId"`
	GroupType    *string `pulumi:"groupType"`
	// The provider-assigned unique ID for this managed resource.
	Id         string                         `pulumi:"id"`
	ItemId     *string                        `pulumi:"itemId"`
	KeyWord    *string                        `pulumi:"keyWord"`
	Protocol   *int                           `pulumi:"protocol"`
	Records    []GetServiceGroupMembersRecord `pulumi:"records"`
	Region     string                         `pulumi:"region"`
	SourcePort *string                        `pulumi:"sourcePort"`
}

func GetServiceGroupMembersOutput(ctx *pulumi.Context, args GetServiceGroupMembersOutputArgs, opts ...pulumi.InvokeOption) GetServiceGroupMembersResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetServiceGroupMembersResultOutput, error) {
			args := v.(GetServiceGroupMembersArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cloudru:Cfw/getServiceGroupMembers:getServiceGroupMembers", args, GetServiceGroupMembersResultOutput{}, options).(GetServiceGroupMembersResultOutput), nil
		}).(GetServiceGroupMembersResultOutput)
}

// A collection of arguments for invoking getServiceGroupMembers.
type GetServiceGroupMembersOutputArgs struct {
	DestPort     pulumi.StringPtrInput `pulumi:"destPort"`
	FwInstanceId pulumi.StringPtrInput `pulumi:"fwInstanceId"`
	GroupId      pulumi.StringInput    `pulumi:"groupId"`
	GroupType    pulumi.StringPtrInput `pulumi:"groupType"`
	ItemId       pulumi.StringPtrInput `pulumi:"itemId"`
	KeyWord      pulumi.StringPtrInput `pulumi:"keyWord"`
	Protocol     pulumi.IntPtrInput    `pulumi:"protocol"`
	Region       pulumi.StringPtrInput `pulumi:"region"`
	SourcePort   pulumi.StringPtrInput `pulumi:"sourcePort"`
}

func (GetServiceGroupMembersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServiceGroupMembersArgs)(nil)).Elem()
}

// A collection of values returned by getServiceGroupMembers.
type GetServiceGroupMembersResultOutput struct{ *pulumi.OutputState }

func (GetServiceGroupMembersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServiceGroupMembersResult)(nil)).Elem()
}

func (o GetServiceGroupMembersResultOutput) ToGetServiceGroupMembersResultOutput() GetServiceGroupMembersResultOutput {
	return o
}

func (o GetServiceGroupMembersResultOutput) ToGetServiceGroupMembersResultOutputWithContext(ctx context.Context) GetServiceGroupMembersResultOutput {
	return o
}

func (o GetServiceGroupMembersResultOutput) DestPort() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) *string { return v.DestPort }).(pulumi.StringPtrOutput)
}

func (o GetServiceGroupMembersResultOutput) FwInstanceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) *string { return v.FwInstanceId }).(pulumi.StringPtrOutput)
}

func (o GetServiceGroupMembersResultOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) string { return v.GroupId }).(pulumi.StringOutput)
}

func (o GetServiceGroupMembersResultOutput) GroupType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) *string { return v.GroupType }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetServiceGroupMembersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetServiceGroupMembersResultOutput) ItemId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) *string { return v.ItemId }).(pulumi.StringPtrOutput)
}

func (o GetServiceGroupMembersResultOutput) KeyWord() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) *string { return v.KeyWord }).(pulumi.StringPtrOutput)
}

func (o GetServiceGroupMembersResultOutput) Protocol() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) *int { return v.Protocol }).(pulumi.IntPtrOutput)
}

func (o GetServiceGroupMembersResultOutput) Records() GetServiceGroupMembersRecordArrayOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) []GetServiceGroupMembersRecord { return v.Records }).(GetServiceGroupMembersRecordArrayOutput)
}

func (o GetServiceGroupMembersResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetServiceGroupMembersResultOutput) SourcePort() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServiceGroupMembersResult) *string { return v.SourcePort }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServiceGroupMembersResultOutput{})
}
